# Generated by Django 2.1.7 on 2019-03-27 22:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('create_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('year', models.CharField(max_length=64)),
                ('rated', models.CharField(max_length=64)),
                ('released', models.CharField(max_length=64)),
                ('runtime', models.CharField(max_length=64)),
                ('genre', models.CharField(max_length=64)),
                ('director', models.CharField(max_length=64)),
                ('writer', models.TextField()),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('awards', models.TextField()),
                ('poster', models.TextField()),
                ('metascore', models.CharField(max_length=64)),
                ('imdb_rating', models.CharField(max_length=64)),
                ('imdb_votes', models.CharField(max_length=64)),
                ('imdb_ID', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('dvd', models.CharField(max_length=64)),
                ('box_office', models.CharField(max_length=64)),
                ('production', models.CharField(max_length=64)),
                ('website', models.TextField()),
                ('response', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Movie'),
        ),
    ]
